### ISSUE TITLE
Uncaught exception 'String could not be parsed as XML'

### ISSUE THREAD

**Issue by jeffnm** [brandon-garcia/NewBooksRSSParser#1]
I'm getting this error in my apache logs. I thought this was working before. Any idea what might be causing it?

PHP Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /data/nd/NewBooksRSSParser/classes/RSSFeed.php:21\nStack trace:\n#0 /data/nd/NewBooksRSSParser/classes/RSSFeed.php(21): SimpleXMLElement->__construct('<?xml version="...')\n#1 /data/nd/NewBooksRSSParser/classes/CarliBookFeed.php(17): RSSFeed->__construct('https://i-share...')\n#2 /data/nd/NewBooksRSSParser/index.php(14): CarliBookFeed->__construct()\n#3 {main}\n  thrown in /data/nd/NewBooksRSSParser/classes/RSSFeed.php on line 21

**Comment by brandon-garcia** [comment]
It's a UTF-8 error. Some characters are not encoded properly in the Carli feed at the moment.

**Comment by brandon-garcia** [comment]
Actually I still need to look into it more, it isn't necessarily a UTF-8 issue.

**Comment by jeffnm** [comment]
Can you import the feed and clean it up into parseable format?

**Comment by brandon-garcia** [comment]
^_        <= found this in the xml (single character)
