### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by jeffnm** [brandon-garcia/NewBooksRSSParser#2]
I pulled the latest patch and now I'm seeing these: 

    PHP Parse error:  syntax error, unexpected T_STRING in /data/nd/NewBooksRSSParser/classes/RSSFeed.php on line 22
    PHP Warning:  Unexpected character in input:  '\\' (ASCII=92) state=1 in /data/nd/NewBooksRSSParser/classes/RSSFeed.php on line 22

**Comment by brandon-garcia** [comment]
What version of PHP did you see this with? The error appears to indicate the use of namespacing, which is only supported in PHP 5.3+

**Comment by jeffnm** [comment]
That was a 5.2 server. I'll check on the 5.4 server on Monday.
